backend:
  name: github
  branch: main
  repo: saralain88/sc-idolfest-website
  cms_label_prefix: web-editor/
  # Comment this next line out to use this locally
  base_url: https://idolfest-auth-picluster.cpprograms.net
# FIXME: If we adopt this, this url obviously needs to change
site_url: https://saralain88.github.io/sc-idolfest-website/
logo_url: https://scidolfest.com/static/2ed145dd599d561ba9a42eb699912d6e/afe0d/socal_test.webp
# This is where it's stored in the repo
media_folder: "/static/images/uploads"
# This is where it is url-wise
public_folder: "/images/uploads"
collections: 
  - name: "root-pages"
    label: "Top-Level"
    folder: "src/markdown-pages/"
    create: true
    delete: true
    slug: "{{slug}}" # (    o_o) slug
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "hidden", default: "page"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "blog-posts"
    label: "Blog"
    # NOTE: This needs to be updated for each event to make blogs work
    folder: "src/markdown-pages/blog/2022"
    create: true
    delete: true
    summary: "{{fields.title}} ({{fields.date}})"
    slug: "{{slug}}" # (    o_o) slug
    sort: 'date:desc'
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, format: "YYYY-MM-DD"}
      - {label: "Template", name: "template", widget: "hidden", default: "blogpost"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "about"
    label: "About Section"
    folder: "src/markdown-pages/about"
    create: true
    delete: true
    slug: "{{slug}}" # (    o_o) slug
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "hidden", default: "page"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "events"
    label: "Events Section"
    folder: "src/markdown-pages/events"
    create: true
    delete: true
    slug: "{{slug}}" # (    o_o) slug
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "hidden", default: "page"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Site Settings"
    name: "general"
    files: 
    - label: "Site Metadata"
      name: "site-metadata"
      file: "siteMetadata.json"
      extension: "json"
      description: "General Site Settings"
      fields:
        - {label: "Global title", name: "title", widget: "string"}
        - {label: "Short Dates", name: "shortDates", widget: "string"}
        - {label: "Long Dates", name: "longDates", widget: "string"}
        - {label: "Location", name: "location", widget: "string"}
        - label: Social
          name: social
          widget: object
          fields: 
            - {label: "Twitter", name: "twitter", widget: "string"}
            - {label: "Facebook", name: "facebook", widget: "string"}
            - {label: "Instagram", name: "instagram", widget: "string"}
            - {label: "Discord", name: "discord", widget: "string"}
            - {label: "Email", name: "email", widget: "string"}
    - label: "Navigation Items"
      name: "navigation"
      file: "src/components/HeaderData.json"
      extension: "json"
      description: "Items to show in site navigation"
      fields: 
        - label: "Navigation Items"
          name: "headersData"
          widget: "list"
          fields: 
            - {label: Label, name: label, widget: string}
            - {label: "Page path (short - eg /register or /guests/phoebe)", name: href, widget: string}
            - {label: "Hidden from Navigation", name: disabled, widget: boolean}
            - {label: "Link to outside website (eg google docs)", name: external, widget: boolean}
